name: Test Workflow Locally

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install uv
          uv sync
          if [ -f testing/requirements-dev.txt ]; then pip install -r testing/requirements-dev.txt; fi

      - name: Run tests
        run: |
          export PYTHONPATH=./src
          pytest -xvs

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Docker image locally
        run: |
          docker build -t kibana-mcp:local .
          docker image ls | grep kibana-mcp
